import {createHash} from 'node:crypto';
import {lstat,readFile,readdir,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import type {Client} from '@modelcontextprotocol/client';
import {afterEach,describe,expect,it} from 'vitest';
import {rbridgeOperationIntentDigest,type RBridgeExecutionReceiptV1} from '../../src/domain/rbridgeExecutionContract.js';
import {connectRBridgeCoreIpcClient} from '../../src/server/rbridgeCoreIpc.js';
import {createRBridgeAcceptanceFixture,type RBridgeAcceptanceFixture} from '../fixtures/rbridge-acceptance-owner.js';
const fixtures:RBridgeAcceptanceFixture[]=[],cleanup:Array<()=>Promise<void>>=[];
afterEach(async()=>{for(const close of cleanup.splice(0).reverse())await close();for(const f of fixtures.splice(0))await f.close();});
async function fixture(){const f=await createRBridgeAcceptanceFixture();fixtures.push(f);return f;}
const object=(result:{structuredContent?:unknown})=>result.structuredContent as Record<string,unknown>;
const hash=(data:Buffer)=>createHash('sha256').update(data).digest('hex');
async function terminal(client:Client,id='shared-acceptance'):Promise<RBridgeExecutionReceiptV1>{const until=Date.now()+10000;while(Date.now()<until){const response=object(await client.callTool({name:'rbridge_status',arguments:{operationId:id}})),result=response.result as {receipt?:RBridgeExecutionReceiptV1}|undefined;if(result?.receipt?.phase==='TERMINAL')return result.receipt;await new Promise<void>(done=>setTimeout(done,5));}throw new Error('ACCEPTANCE_TERMINAL_DEADLINE');}
const submit=(client:Client,f:RBridgeAcceptanceFixture,id='shared-acceptance',operation=f.submission().operation)=>client.callTool({name:'rbridge_submit',arguments:{operationId:id,operation}});
async function output(client:Client,id='shared-acceptance'){const row=object(await client.callTool({name:'rbridge_result',arguments:{operationId:id,cursor:0,maxBytes:32768}})).result as {receipt:RBridgeExecutionReceiptV1;dataBase64:string;resultSha256:string};const bytes=Buffer.from(row.dataBase64,'base64');expect(hash(bytes)).toBe(row.resultSha256);return {row,bytes,value:JSON.parse(bytes.toString()) as Record<string,unknown>};}
describe('assembled owner, actual SDK processes and authenticated GitHub acceptance',()=>{
 it('two stdio clients and GitHub converge on one operation',async()=>{const f=await fixture(),actor=await f.start({holdRead:true}),modern=await f.stdio('modern'),legacy=await f.stdio('legacy'),issue=f.issue();const admissions=await Promise.all([submit(modern,f),submit(legacy,f),actor.request('ADMIT',issue)]);expect(object(admissions[0] as Awaited<ReturnType<typeof submit>>).status).toBe('CORE_RECEIPT');expect(object(admissions[1] as Awaited<ReturnType<typeof submit>>).status).toBe('CORE_RECEIPT');expect(admissions[2]).toBe('CORE');await actor.event('READ_ENTERED');await actor.request('RELEASE_READ');const a=await terminal(modern),b=await terminal(legacy);await actor.request('DRAIN');const carrier=JSON.parse(f.comments.get(issue.number)![0]!.body.slice(8,-5)) as {operationResult:{receipt:RBridgeExecutionReceiptV1;output:unknown}};expect(a).toEqual(b);expect(carrier.operationResult.receipt).toEqual(a);const read=await output(modern);expect(read.value).toMatchObject({text:'acceptance source\n'});expect(carrier.operationResult.output).toEqual(read.value);expect(await actor.request('COUNTS')).toMatchObject({reads:1});expect(f.issues.get(issue.number)!.state).toBe('closed');},30000);
 it('replacement owner preserves terminal truth and recovers a lost remote close acknowledgement',async()=>{const f=await fixture(),actor=await f.start(),client=await f.stdio('modern'),issue=f.issue();await submit(client,f);const receipt=await terminal(client),record=await readFile(join(f.root,'operations','shared-acceptance.json')),inode=(await lstat(join(f.root,'owner.lock'))).ino;f.failCloseOnce();await actor.request('ADMIT',issue);expect(f.issues.get(issue.number)!.state).toBe('closed');expect(JSON.parse(await readFile(join(f.root,'deliveries','github',issue.number+'.json'),'utf8')).state).toBe('PENDING');await actor.kill();expect(object(await client.callTool({name:'rbridge_capabilities',arguments:{}}))).toMatchObject({executionAvailable:false});const replacement=await f.start(),reconnected=await f.stdio('legacy');expect(await terminal(reconnected)).toEqual(receipt);await replacement.request('DRAIN');expect(await replacement.request('COUNTS')).toMatchObject({reads:0});expect(await readFile(join(f.root,'operations','shared-acceptance.json'))).toEqual(record);expect((await lstat(join(f.root,'owner.lock'))).ino).toBe(inode);expect(f.comments.get(issue.number)).toHaveLength(1);expect(JSON.parse(await readFile(join(f.root,'deliveries','github',issue.number+'.json'),'utf8')).state).toBe('PUBLISHED');},30000);
 it('a SIGKILL during a real read reobserves the incomplete operation once after restart',async()=>{const f=await fixture(),actor=await f.start({holdRead:true}),client=await f.stdio('modern');await submit(client,f);await actor.event('READ_ENTERED');await actor.kill();await writeFile(join(f.sourceRoot,'source.txt'),'changed after owner death\n',{mode:0o600});const replacement=await f.start(),reconnected=await f.stdio('modern');expect((await terminal(reconnected)).outcome).toBe('PASS');expect((await output(reconnected)).value).toMatchObject({text:'changed after owner death\n'});expect(await replacement.request('COUNTS')).toMatchObject({reads:1});},30000);
 it('intent collisions cannot replace a terminal result or execute another handler',async()=>{const f=await fixture(),actor=await f.start(),client=await f.stdio('modern');await submit(client,f);const receipt=await terminal(client),bytes=await readFile(join(f.root,'operations','shared-acceptance.json'));expect(object(await submit(client,f,'shared-acceptance',{kind:'HEALTH',action:'STATUS'}))).toMatchObject({status:'BLOCKED',reason:'RBRIDGE_CORE_INTENT_COLLISION'});expect(await terminal(client)).toEqual(receipt);expect(await readFile(join(f.root,'operations','shared-acceptance.json'))).toEqual(bytes);expect(await actor.request('COUNTS')).toMatchObject({reads:1,health:0});},30000);
 it('queued and running cancellation wait for the actual health handler to settle',async()=>{const f=await fixture(),actor=await f.start({holdHealth:true}),client=await f.stdio('modern'),operation={kind:'HEALTH',action:'STATUS'} as const;for(let n=1;n<=4;n++)await submit(client,f,'held-'+n,operation);await actor.event('HEALTH_ENTERED',4);await submit(client,f,'queued',operation);for(const id of ['queued','held-1'])expect(object(await client.callTool({name:'rbridge_cancel',arguments:{operationId:id,intentSha256:rbridgeOperationIntentDigest(f.submission(id,operation))}}))).toMatchObject({result:{status:'REQUESTED'}});expect((await terminal(client,'queued')).outcome).toBe('TERMINATED');expect(object(await client.callTool({name:'rbridge_status',arguments:{operationId:'held-1'}}))).toMatchObject({result:{receipt:{phase:'RUNNING',cancellation:{state:'REQUESTED'}}}});expect(await actor.request('COUNTS')).toMatchObject({health:4});await actor.request('RELEASE_HEALTH');expect(await terminal(client,'held-1')).toMatchObject({outcome:'TERMINATED',sideEffects:{state:'NONE_PROVEN'}});},30000);
 it('a lost real admission acknowledgement keeps one durable claim and never reports a false PASS',async()=>{const f=await fixture(),actor=await f.start({holdClaim:true}),client=await connectRBridgeCoreIpcClient({root:f.root,expectedBinding:f.binding});cleanup.push(()=>client.close());const controller=new AbortController(),pending=client.submit(f.submission(),f.context,controller.signal),rejected=expect(pending).rejects.toThrow();await actor.event('CLAIM_ACK_HELD');controller.abort();await actor.request('RELEASE_CLAIM');await rejected;const sdk=await f.stdio('modern'),receipt=await terminal(sdk);expect(receipt).toMatchObject({outcome:'TERMINATED',cancellation:{state:'REQUESTED'},sideEffects:{state:'NONE_PROVEN'}});expect(receipt.transitions.filter(t=>t.phase==='CLAIMED')).toHaveLength(1);expect(await actor.request('COUNTS')).toMatchObject({reads:0});},30000);
 it('full result storage retains failed bytes and cannot publish PASS',async()=>{const f=await fixture(),actor=await f.start({fullResult:true}),client=await f.stdio('modern');await submit(client,f);const receipt=await terminal(client);expect(receipt).toMatchObject({outcome:'FAIL',reason:'RBRIDGE_CORE_RESULT_COMMIT_FAILED'});expect(receipt.resultSha256).toBeUndefined();expect((await readdir(join(f.root,'results'))).some(name=>name.endsWith('.stage'))).toBe(true);await actor.request('ADMIT',f.issue());expect(JSON.parse(f.comments.get(17)![0]!.body.slice(8,-5))).toMatchObject({status:'FAIL',operationResult:{receipt:{outcome:'FAIL'}}});expect(await actor.request('COUNTS')).toMatchObject({reads:1});},30000);
 it('manifest mismatch and corruption refuse replacement while retaining evidence',async()=>{const f=await fixture(),actor=await f.start(),client=await f.stdio('modern');await submit(client,f);await terminal(client);await actor.close();const manifest=await readFile(join(f.root,'manifest.json'));await expect(f.start({target:'wrong-target'})).rejects.toThrow('ACCEPTANCE_OWNER_STARTUP_FAILED');expect(await readFile(join(f.root,'manifest.json'))).toEqual(manifest);const path=join(f.root,'operations','shared-acceptance.json');await writeFile(path,'retained-corruption',{mode:0o600});await expect(f.start()).rejects.toThrow('ACCEPTANCE_OWNER_STARTUP_FAILED');expect(await readFile(path,'utf8')).toBe('retained-corruption');await expect(lstat(join(f.root,'core.sock'))).rejects.toMatchObject({code:'ENOENT'});},30000);
 it('real default reservation exhaustion rejects a new ID while known status stays available',async()=>{const f=await fixture(),actor=await f.start({holdHealth:true}),client=await f.stdio('modern'),operation={kind:'HEALTH',action:'STATUS'} as const;for(let n=0;n<32;n++)expect(object(await submit(client,f,'capacity-'+n,operation)).status).toBe('CORE_RECEIPT');expect(object(await submit(client,f,'capacity-extra',operation))).toMatchObject({status:'BLOCKED',reason:'RBRIDGE_CORE_CAPACITY_REACHED'});expect(object(await client.callTool({name:'rbridge_status',arguments:{operationId:'capacity-0'}}))).toMatchObject({result:{status:'RECEIPT'}});expect(await actor.request('COUNTS')).toMatchObject({health:4});await actor.request('RELEASE_HEALTH');expect((await terminal(client,'capacity-31')).outcome).toBe('PASS');},30000);
});
