import {lstat,mkdtemp,readFile,readdir,rm,symlink,writeFile} from 'node:fs/promises';
import {homedir,userInfo} from 'node:os';
import {join} from 'node:path';
import {afterEach,describe,expect,it} from 'vitest';
import type {GitHubBridgeIssue,RBridgeGitHubComment} from '../../src/adapters/githubIssueRemoteBridge.js';
import type {RBridgeOperationSubmissionV1,RBridgeTransportContextV1} from '../../src/domain/rbridgeExecutionContract.js';
import {startRBridgeOwnerRuntime,type RBridgeOwnerRuntime,type RBridgeOwnerRuntimeOptions} from '../../src/server/rbridgeOwnerRuntime.js';
import {acquireRemoteBridgeProcessLock} from '../../src/server/remoteBridgeStore.js';
import {acquireRBridgeOwnerLock,assertRBridgeOwnerLockHeld} from '../../src/server/rbridgeOwnerLock.js';
import {connectRBridgeCoreIpcClient} from '../../src/server/rbridgeCoreIpc.js';
import {createRBridgeStateFiles} from '../../src/server/rbridgeStateFiles.js';
const roots:string[]=[],owners:RBridgeOwnerRuntime[]=[],relays:Array<{release():Promise<void>}>=[],gates:Array<()=>void>=[];
afterEach(async()=>{for(const release of gates.splice(0))release();for(const owner of owners.splice(0))await owner.close();for(const relay of relays.splice(0))await relay.release();for(const root of roots.splice(0))await rm(root,{recursive:true,force:true});});
function gate(){let release!:()=>void;const promise=new Promise<void>(done=>release=done);gates.push(release);return {promise,release};}
async function fixture(lock=true){
  const user=userInfo(),uid=process.getuid!();if(uid<=0||process.geteuid!()!==uid)throw new Error('TEST_NONROOT_OWNER_REQUIRED');
  const home=await mkdtemp(join(homedir(),'.rbridge-runtime-'));roots.push(home);
  const files=createRBridgeStateFiles({checkFilesystem:async()=>undefined});
  const parent=join(home,'.local','state','rbridge'),root=join(parent,'execution-v2');
  for(const path of [join(home,'.local'),join(home,'.local','state'),parent])await files.ensureDirectory(path,uid);
  const relay=lock?await acquireRemoteBridgeProcessLock(parent):undefined;if(relay)relays.push(relay);
  const issues=new Map<number,GitHubBridgeIssue&{state:'open'|'closed'}>(),comments=new Map<number,RBridgeGitHubComment[]>();let commentId=1,healthCalls=0;
  const binding={runtimeUid:uid,principalId:'operator-test',targetInstanceId:'target-test'};
  const context:RBridgeTransportContextV1={schema:'RBRIDGE_TRANSPORT_CONTEXT_V1',transport:'MCP',authenticatedSubject:`uid:${uid}`,principalId:binding.principalId};
  const submission=(operationId='runtime-health',operation:RBridgeOperationSubmissionV1['operation']={kind:'HEALTH',action:'STATUS'}):RBridgeOperationSubmissionV1=>({schema:'RBRIDGE_OPERATION_SUBMISSION_V1',operationId,principalId:binding.principalId,targetInstanceId:binding.targetInstanceId,operation});
  const options:RBridgeOwnerRuntimeOptions={runtimeIdentity:{username:user.username,homedir:home,uid,euid:uid},env:{RBRIDGE_RUNTIME_USER:user.username,RBRIDGE_INSTANCE_ID:binding.targetInstanceId,RBRIDGE_MCP_PRINCIPAL_ID:binding.principalId,RBRIDGE_GITHUB_REPOSITORY:'example/control',RBRIDGE_GITHUB_AUTHOR:'owner'},files,health:{snapshot(){healthCalls++;return {schema:'COCWIN_REMOTE_BRIDGE_HEALTH_V2',status:'PASS',releaseSha:'1'.repeat(40),uptimeMs:0,queueCount:0,sessionCount:0,transferCount:0,lastGitHubPollAt:null};}},github:{async listOpenRequests(){return [...issues.values()].filter(i=>i.state==='open');},async publishResult(){throw new Error('TEST_LEGACY_PUBLICATION_FORBIDDEN');},async readIssue(number){return structuredClone(issues.get(number)!);},async readCommentPage(number,page){return structuredClone((comments.get(number)??[]).slice((page-1)*20,page*20));},async postComment(number,body){const id=commentId++,row={id,body,authorLogin:'owner',url:`https://github.com/example/control/issues/${number}#issuecomment-${id}`};comments.set(number,[...(comments.get(number)??[]),row]);return row;},async closeIssue(number){issues.get(number)!.state='closed';}}};
  const start=async(overrides:Partial<RBridgeOwnerRuntimeOptions>={})=>{const owner=await startRBridgeOwnerRuntime({...options,...overrides});owners.push(owner);return owner;};
  return {home,parent,root,uid,files,relay,binding,context,submission,options,start,issues,comments,get healthCalls(){return healthCalls;}};
}
async function terminal(owner:RBridgeOwnerRuntime,f:Awaited<ReturnType<typeof fixture>>,id:string){const until=Date.now()+5000;while(Date.now()<until){const row=await owner.core.status(id,f.context);if(row.status==='RECEIPT'&&row.receipt.phase==='TERMINAL')return row.receipt;await new Promise<void>(done=>setTimeout(done,5));}throw new Error('TEST_TERMINAL_DEADLINE');}
describe('assembled relay owner runtime',()=>{
  it('rejects root identity before creating state',async()=>{const home=await mkdtemp(join(homedir(),'.rbridge-runtime-negative-'));roots.push(home);await expect(startRBridgeOwnerRuntime({runtimeIdentity:{username:'root',uid:0,euid:0,homedir:home},env:{RBRIDGE_RUNTIME_USER:'root'},github:{} as RBridgeOwnerRuntimeOptions['github'],health:{snapshot:()=>({})}})).rejects.toThrow('RBRIDGE_MCP_RUNTIME_IDENTITY_INVALID');expect(await readdir(home)).toEqual([]);});
  it('requires explicit binding before any new owner files',async()=>{const f=await fixture();for(const key of ['RBRIDGE_INSTANCE_ID','RBRIDGE_MCP_PRINCIPAL_ID']){const env={...f.options.env};delete env[key];await expect(f.start({env})).rejects.toThrow('RBRIDGE_MCP_BINDING_INVALID');}expect(await readdir(f.parent)).toEqual(['relay.lock']);});
  it('requires the actual already-held relay exclusion, not a matching PID file',async()=>{const f=await fixture(false);await writeFile(join(f.parent,'relay.lock'),String(process.pid)+'\n',{mode:0o600});await expect(f.start()).rejects.toThrow('RBRIDGE_OWNER_RELAY_LOCK_REQUIRED');expect(await readdir(f.parent)).toEqual(['relay.lock']);});
  it('locks precede every writer and socket, and isolates legacy files from core accounting',async()=>{const f=await fixture();await writeFile(join(f.parent,'legacy.json'),'preserved',{mode:0o600});const events:string[]=[],commit=f.files.commit;const files={...f.files,async commit(...args:Parameters<typeof commit>){assertRBridgeOwnerLockHeld(f.root);events.push('owner-held-write');return commit(...args);}};const owner=await f.start({files});expect(events.length).toBeGreaterThan(0);const client=await connectRBridgeCoreIpcClient({root:f.root,expectedBinding:f.binding,files:f.files});try{expect((await client.binding()).enabledActions).toContain('HEALTH/STATUS');await client.submit(f.submission(),f.context,new AbortController().signal);expect((await terminal(owner,f,'runtime-health')).outcome).toBe('PASS');expect(f.healthCalls).toBe(1);}finally{await client.close();}expect(await readFile(join(f.parent,'legacy.json'),'utf8')).toBe('preserved');await expect(acquireRBridgeOwnerLock({root:f.root,uid:f.uid,files:f.files})).rejects.toThrow();});
  it('manifest mismatch retains bytes and releases only the failed owner lock',async()=>{const f=await fixture(),owner=await f.start();await owner.close();const before=await readFile(join(f.root,'manifest.json'));await expect(f.start({env:{...f.options.env,RBRIDGE_INSTANCE_ID:'other-target'}})).rejects.toThrow();expect(await readFile(join(f.root,'manifest.json'))).toEqual(before);expect((await lstat(join(f.parent,'relay.lock'))).isFile()).toBe(true);const lock=await acquireRBridgeOwnerLock({root:f.root,uid:f.uid,files:f.files});await lock.close();});
  it('partial IPC startup failure retains unsafe socket evidence and releases the owner FD',async()=>{const f=await fixture();await f.files.ensureDirectory(f.root,f.uid);const target=join(f.home,'retained.txt');await writeFile(target,'evidence',{mode:0o600});await symlink(target,join(f.root,'core.sock'));await expect(f.start()).rejects.toThrow();expect((await lstat(join(f.root,'core.sock'))).isSymbolicLink()).toBe(true);expect(await readFile(target,'utf8')).toBe('evidence');const lock=await acquireRBridgeOwnerLock({root:f.root,uid:f.uid,files:f.files});await lock.close();expect((await lstat(join(f.parent,'relay.lock'))).isFile()).toBe(true);});
  it('recovery refuses corrupt records without publishing a socket or rewriting evidence',async()=>{const f=await fixture(),owner=await f.start();await owner.core.submit(f.submission(),f.context,new AbortController().signal);await terminal(owner,f,'runtime-health');await owner.close();const path=join(f.root,'operations','runtime-health.json');await writeFile(path,'corrupt-retained',{mode:0o600});await expect(f.start()).rejects.toThrow();expect(await readFile(path,'utf8')).toBe('corrupt-retained');await expect(lstat(join(f.root,'core.sock'))).rejects.toMatchObject({code:'ENOENT'});const lock=await acquireRBridgeOwnerLock({root:f.root,uid:f.uid,files:f.files});await lock.close();});
  it('cleanup retains exclusion until real handlers and lifecycle work settle',async()=>{const f=await fixture(),handler=gate(),flow=gate(),entered=gate();const owner=await f.start({health:{async snapshot(){entered.release();await handler.promise;return f.options.health.snapshot();}}});await owner.core.submit(f.submission(),f.context,new AbortController().signal);await entered.promise;let closed=false,flowEntered=false;const closing=owner.close(async()=>{flowEntered=true;await flow.promise;}).then(()=>{closed=true;});await new Promise<void>(done=>setTimeout(done,30));expect(closed).toBe(false);expect(flowEntered).toBe(false);assertRBridgeOwnerLockHeld(f.root);await expect(acquireRBridgeOwnerLock({root:f.root,uid:f.uid,files:f.files})).rejects.toThrow();handler.release();for(let n=0;n<100&&!flowEntered;n++)await new Promise<void>(done=>setTimeout(done,5));expect(flowEntered).toBe(true);expect(closed).toBe(false);assertRBridgeOwnerLockHeld(f.root);flow.release();await closing;expect(closed).toBe(true);expect(()=>assertRBridgeOwnerLockHeld(f.root)).toThrow();const lock=await acquireRBridgeOwnerLock({root:f.root,uid:f.uid,files:f.files});await lock.close();expect((await lstat(join(f.parent,'relay.lock'))).isFile()).toBe(true);});
  it('new SAFE mutation has a durable core BLOCK without legacy publication or health work',async()=>{const f=await fixture(),owner=await f.start(),now=new Date(),id='blocked-write',issue={number:17,title:'[COCWIN BRIDGE REQUEST] '+id,body:JSON.stringify({schema:'COCWIN_REMOTE_BRIDGE_REQUEST_V2',requestId:id,createdAt:now.toISOString(),expiresAt:new Date(now.getTime()+600000).toISOString(),operation:{kind:'FILE',action:'WRITE_TEXT',target:'/mnt/data/blocked.txt',args:{text:'blocked'}}}),authorLogin:'owner',url:'https://github.com/example/control/issues/17',state:'open' as const};f.issues.set(17,issue);expect(await owner.githubCore.admit(issue)).toBe('CORE');const receipt=await terminal(owner,f,id);expect(receipt.outcome).toBe('BLOCKED');expect(f.healthCalls).toBe(0);expect(f.comments.get(17)).toHaveLength(1);expect(f.issues.get(17)!.state).toBe('closed');await expect(lstat(join(f.parent,id+'.json'))).rejects.toMatchObject({code:'ENOENT'});});
});
