import type {GitHubBridgeIssue} from '../../src/adapters/githubIssueRemoteBridge.js';
import {createHash} from 'node:crypto';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {afterEach,describe,expect,it,vi} from 'vitest';
import {createRemoteBridgeStore} from '../../src/server/remoteBridgeStore.js';import {createRemoteBridgeWorker} from '../../src/server/remoteBridgeWorker.js';
const TRANSPORT={repository:'example/rbridge-control',authorLogin:'bridge-owner',instanceId:'test-instance'} as const;
const roots:string[]=[];async function root(){const p=await mkdtemp(join(tmpdir(),'bridge-worker-'));roots.push(p);return p;}afterEach(async()=>{await Promise.all(roots.splice(0).map(p=>rm(p,{recursive:true,force:true})));});
const body=(max=262144)=>JSON.stringify({schema:'COCWIN_REMOTE_BRIDGE_REQUEST_V1',requestId:'bridge.req.1',createdAt:'2026-09-16T18:00:00.000Z',expiresAt:'2026-09-16T18:20:00.000Z',appId:'cocwin',jobId:'bridge-probe-1',operation:'RUN',payload:{tool:'probe',cwd:'/home/cocwin/backend',args:[],timeout_ms:30000,max_bytes:max}});
const issue=(number=49,max=262144)=>({number,title:'[COCWIN BRIDGE REQUEST] bridge.req.1',body:body(max),authorLogin:'bridge-owner',url:`https://github.com/example/rbridge-control/issues/${number}`});
const now=()=>new Date('2026-09-16T18:10:00.000Z');
const sha=(value:Buffer|string)=>createHash('sha256').update(value).digest('hex');
const chunk=Buffer.from('chunk-worker-payload');
const chunkArgs={index:0,count:1,dataBase64:chunk.toString('base64'),chunkSha256:sha(chunk),objectSha256:sha(chunk),expiresAt:'2026-09-16T18:20:00.000Z'};
const v2ChunkBody=(requestId='bridge.chunk.1',args:Record<string,unknown>=chunkArgs)=>JSON.stringify({schema:'COCWIN_REMOTE_BRIDGE_REQUEST_V2',requestId,createdAt:'2026-09-16T18:00:00.000Z',expiresAt:'2026-09-16T18:20:00.000Z',operation:{kind:'CHUNK',action:'PUT',transferId:'tx.worker',args}});
const v2ChunkIssue=(number=70,requestId='bridge.chunk.1',args:Record<string,unknown>=chunkArgs)=>({number,title:`[COCWIN BRIDGE REQUEST] ${requestId}`,body:v2ChunkBody(requestId,args),authorLogin:'bridge-owner',url:`https://github.com/example/rbridge-control/issues/${number}`});
const controller=()=>({submit:vi.fn(),status:vi.fn(),result:vi.fn()});
const resultPut=(state:'STORED'|'REPLAY')=>vi.fn(async(input:unknown)=>{void input;return {state,index:0};});
const chunkPort=(put=resultPut('STORED'))=>({putChunk:put,getChunk:vi.fn(),finalizeTransfer:vi.fn()});

describe('remote bridge worker',()=>{
 it('durably marks SUBMITTED before first submit and leaves request pending when queued',async()=>{const dir=await root(),events:string[]=[];const store=createRemoteBridgeStore(dir,now),published:unknown[]=[];const worker=createRemoteBridgeWorker({...TRANSPORT,now,store,github:{listOpenRequests:async()=>[issue()],publishResult:async(_n,r)=>{published.push(r);}},controller:{submit:async()=>{events.push('submit');expect((await store.get('bridge.req.1'))?.phase).toBe('SUBMITTED');return {state:'QUEUED'};},status:vi.fn(),result:vi.fn()}});const out=await worker.runOnce();expect(out).toMatchObject({seen:1,pending:1,published:0});expect(events).toEqual(['submit']);expect(published).toHaveLength(0);});
 it('reconciles a durable SUBMITTED request by status/result without resubmitting',async()=>{const dir=await root(),store=createRemoteBridgeStore(dir,now);const worker1=createRemoteBridgeWorker({...TRANSPORT,now,store,github:{listOpenRequests:async()=>[issue()],publishResult:vi.fn()},controller:{submit:async()=>{throw new Error('transport lost after possible submit');},status:vi.fn(),result:vi.fn()}});await worker1.runOnce();expect((await store.get('bridge.req.1'))?.phase).toBe('SUBMITTED');const submit=vi.fn(),publish=vi.fn();const worker2=createRemoteBridgeWorker({...TRANSPORT,now,store,github:{listOpenRequests:async()=>[issue()],publishResult:publish},controller:{submit,status:async()=>({state:'SUCCEEDED'}),result:async()=>({schema:'COCWIN_APP_EXECUTION_RESULT_V1',app:'cocwin',job:'bridge-probe-1',state:'SUCCEEDED',returncode:0,stdout:'ok',stderr:'',timed_out:false,truncated:false})}});await worker2.runOnce();expect(submit).not.toHaveBeenCalled();expect(publish).toHaveBeenCalledTimes(1);expect(publish.mock.calls[0]![1]).toMatchObject({schema:'COCWIN_REMOTE_BRIDGE_RESULT_V1',requestId:'bridge.req.1',issueNumber:49,status:'PASS'});expect((await store.get('bridge.req.1'))?.phase).toBe('PUBLISHED');});
 it('replays terminal execution to a duplicate issue without execution and blocks digest collision',async()=>{const dir=await root(),store=createRemoteBridgeStore(dir,now),submit=vi.fn(),publish=vi.fn();const first=createRemoteBridgeWorker({...TRANSPORT,now,store,github:{listOpenRequests:async()=>[issue()],publishResult:async()=>{}},controller:{submit:async()=>({state:'SUCCEEDED'}),status:vi.fn(),result:async()=>({schema:'COCWIN_APP_EXECUTION_RESULT_V1',app:'cocwin',job:'bridge-probe-1',state:'SUCCEEDED',returncode:0,stdout:'ok',stderr:'',timed_out:false,truncated:false})}});await first.runOnce();const replay=createRemoteBridgeWorker({...TRANSPORT,now,store,github:{listOpenRequests:async()=>[issue(50)],publishResult:publish},controller:{submit,status:vi.fn(),result:vi.fn()}});await replay.runOnce();expect(submit).not.toHaveBeenCalled();expect(publish.mock.calls[0]![0]).toBe(50);expect(publish.mock.calls[0]![1]).toMatchObject({status:'PASS',reason:'REPLAY'});const collision=createRemoteBridgeWorker({...TRANSPORT,now,store,github:{listOpenRequests:async()=>[issue(51,262145)],publishResult:publish},controller:{submit,status:vi.fn(),result:vi.fn()}});await collision.runOnce();expect(publish.mock.calls.at(-1)![1]).toMatchObject({status:'BLOCKED',reason:'REQUEST_ID_COLLISION'});expect(submit).not.toHaveBeenCalled();});
 it('terminalizes a definitive controller BLOCKED during reconciliation without calling result or resubmitting',async()=>{const dir=await root(),store=createRemoteBridgeStore(dir,now);const first=createRemoteBridgeWorker({...TRANSPORT,now,store,github:{listOpenRequests:async()=>[issue()],publishResult:vi.fn()},controller:{submit:async()=>({state:'QUEUED'}),status:vi.fn(),result:vi.fn()}});await first.runOnce();expect((await store.get('bridge.req.1'))?.phase).toBe('SUBMITTED');const submit=vi.fn(),result=vi.fn(async()=>({state:'SUCCEEDED'})),publish=vi.fn();const second=createRemoteBridgeWorker({...TRANSPORT,now,store,github:{listOpenRequests:async()=>[issue()],publishResult:publish},controller:{submit,status:async()=>({schema:'COCWIN_APP_EXECUTION_STATUS_V1',app:'cocwin',job:'bridge-probe-1',state:'BLOCKED',reason:'application execution identity is not configured'}),result}});await second.runOnce();expect(submit).not.toHaveBeenCalled();expect(result).not.toHaveBeenCalled();expect(publish).toHaveBeenCalledTimes(1);expect(publish.mock.calls[0]![1]).toMatchObject({status:'BLOCKED',reason:'application execution identity is not configured'});expect((await store.get('bridge.req.1'))?.phase).toBe('PUBLISHED');});
 it('blocks stale or malformed requests without touching controller',async()=>{const dir=await root(),store=createRemoteBridgeStore(dir,()=>new Date('2026-09-16T18:25:00.000Z')),submit=vi.fn(),publish=vi.fn();const worker=createRemoteBridgeWorker({...TRANSPORT,now:()=>new Date('2026-09-16T18:25:00.000Z'),store,github:{listOpenRequests:async()=>[issue()],publishResult:publish},controller:{submit,status:vi.fn(),result:vi.fn()}});await worker.runOnce();expect(submit).not.toHaveBeenCalled();expect(publish.mock.calls[0]![1]).toMatchObject({status:'BLOCKED',reason:'REMOTE_BRIDGE_REQUEST_EXPIRED'});});
 it('terminates durable SUBMITTED request when controller status proves definitive BLOCKED',async()=>{const dir=await root(),store=createRemoteBridgeStore(dir,now);const {parseRemoteBridgeRequest,remoteBridgeRequestDigest}=await import('../../src/domain/remoteBridgeProtocol.js');const q=parseRemoteBridgeRequest({title:issue().title,body:issue().body,authorLogin:'bridge-owner',expectedAuthorLogin:TRANSPORT.authorLogin,now:now()});const d=remoteBridgeRequestDigest(q);await store.claim({requestId:q.requestId,requestSha256:d,scopeSha256:sha(JSON.stringify({repository:TRANSPORT.repository,authorLogin:TRANSPORT.authorLogin,instanceId:TRANSPORT.instanceId})),issueNumber:49,jobId:q.jobId});await store.markSubmitted(q.requestId,d);const submit=vi.fn(),result=vi.fn(),publish=vi.fn();const worker=createRemoteBridgeWorker({...TRANSPORT,now,store,github:{listOpenRequests:async()=>[issue()],publishResult:publish},controller:{submit,status:async()=>({schema:'COCWIN_APP_EXECUTION_STATUS_V1',app:'cocwin',job:'bridge-probe-1',state:'BLOCKED',reason:'application execution identity is not configured'}),result}});const out=await worker.runOnce();expect(submit).not.toHaveBeenCalled();expect(result).not.toHaveBeenCalled();expect(out).toMatchObject({seen:1,pending:0,published:1,blocked:1,errors:0});expect(publish.mock.calls[0]![1]).toMatchObject({status:'BLOCKED',reason:'application execution identity is not configured'});expect((await store.get(q.requestId))?.phase).toBe('PUBLISHED');});
 it('routes a V2 CHUNK PUT through the durable chunk port without touching controller',async()=>{const dir=await root(),store=createRemoteBridgeStore(dir,now),publish=vi.fn(),put=resultPut('STORED'),ctl=controller();const worker=createRemoteBridgeWorker({...TRANSPORT,now,store,github:{listOpenRequests:async()=>[v2ChunkIssue()],publishResult:publish},controller:ctl,chunkStore:chunkPort(put)});const out=await worker.runOnce();expect(out).toMatchObject({seen:1,pending:0,published:1,blocked:0,errors:0});expect(put).toHaveBeenCalledOnce();expect(put.mock.calls[0]![0]).toEqual({transferId:'tx.worker',...chunkArgs});expect(ctl.submit).not.toHaveBeenCalled();expect(publish.mock.calls[0]![1]).toMatchObject({schema:'COCWIN_REMOTE_BRIDGE_RESULT_V2',requestId:'bridge.chunk.1',status:'PASS',operationResult:{state:'STORED',index:0}});expect((await store.get('bridge.chunk.1'))?.phase).toBe('PUBLISHED');});
 it('replays a published V2 chunk request without executing the chunk port twice',async()=>{const dir=await root(),store=createRemoteBridgeStore(dir,now),put=resultPut('STORED'),port=chunkPort(put);const first=createRemoteBridgeWorker({...TRANSPORT,now,store,github:{listOpenRequests:async()=>[v2ChunkIssue()],publishResult:vi.fn()},controller:controller(),chunkStore:port});await first.runOnce();const publish=vi.fn();const replay=createRemoteBridgeWorker({...TRANSPORT,now,store,github:{listOpenRequests:async()=>[v2ChunkIssue(71)],publishResult:publish},controller:controller(),chunkStore:port});await replay.runOnce();expect(put).toHaveBeenCalledTimes(1);expect(publish.mock.calls[0]![1]).toMatchObject({schema:'COCWIN_REMOTE_BRIDGE_RESULT_V2',status:'PASS',reason:'REPLAY'});});
 it('retries a durable SUBMITTED V2 chunk operation after a crash using the same idempotent transfer identity',async()=>{const dir=await root(),store=createRemoteBridgeStore(dir,now),crashing=vi.fn(async(input:unknown)=>{void input;throw new Error('simulated crash after durable SUBMITTED');});const first=createRemoteBridgeWorker({...TRANSPORT,now,store,github:{listOpenRequests:async()=>[v2ChunkIssue()],publishResult:vi.fn()},controller:controller(),chunkStore:chunkPort(crashing)});const firstOut=await first.runOnce();expect(firstOut.errors).toBe(1);expect((await store.get('bridge.chunk.1'))?.phase).toBe('SUBMITTED');const resumed=resultPut('REPLAY'),publish=vi.fn();const second=createRemoteBridgeWorker({...TRANSPORT,now,store,github:{listOpenRequests:async()=>[v2ChunkIssue()],publishResult:publish},controller:controller(),chunkStore:chunkPort(resumed)});await second.runOnce();expect(resumed).toHaveBeenCalledOnce();expect(publish.mock.calls[0]![1]).toMatchObject({schema:'COCWIN_REMOTE_BRIDGE_RESULT_V2',status:'PASS',operationResult:{state:'REPLAY',index:0}});expect((await store.get('bridge.chunk.1'))?.phase).toBe('PUBLISHED');});

 it('continues tracking an accepted V1 request after its acceptance TTL expires',async()=>{
   const dir=await root();let clock=new Date('2026-09-16T18:10:00.000Z');const tick=()=>clock;
   const store=createRemoteBridgeStore(dir,tick);
   const first=createRemoteBridgeWorker({...TRANSPORT,now:tick,store,github:{listOpenRequests:async()=>[issue()],publishResult:vi.fn()},controller:{submit:async()=>({state:'QUEUED'}),status:vi.fn(),result:vi.fn()}});
   await first.runOnce();expect((await store.get('bridge.req.1'))?.phase).toBe('SUBMITTED');
   clock=new Date('2026-09-16T18:25:00.000Z');
   const status=vi.fn(async()=>({state:'SUCCEEDED'})),result=vi.fn(async()=>({schema:'COCWIN_APP_EXECUTION_RESULT_V1',app:'cocwin',job:'bridge-probe-1',state:'SUCCEEDED',returncode:0,stdout:'ok',stderr:'',timed_out:false,truncated:false})),publish=vi.fn();
   const resumed=createRemoteBridgeWorker({...TRANSPORT,now:tick,store,github:{listOpenRequests:async()=>[issue()],publishResult:publish},controller:{submit:vi.fn(),status,result}});
   const out=await resumed.runOnce();
   expect(out).toMatchObject({seen:1,pending:0,published:1,blocked:0,errors:0});
   expect(status).toHaveBeenCalledOnce();expect(result).toHaveBeenCalledOnce();
   expect(publish.mock.calls[0]![1]).toMatchObject({status:'PASS'});
 });

 it('continues tracking an accepted V2 APP_RUN after its acceptance TTL expires',async()=>{
   const dir=await root();let clock=new Date('2026-09-16T18:10:00.000Z');const tick=()=>clock;
   const store=createRemoteBridgeStore(dir,tick),requestId='bridge.v2.expiry.1';
   const v2={number:81,title:`[COCWIN BRIDGE REQUEST] ${requestId}`,authorLogin:TRANSPORT.authorLogin,url:'https://github.com/example/rbridge-control/issues/81',body:JSON.stringify({schema:'COCWIN_REMOTE_BRIDGE_REQUEST_V2',requestId,createdAt:'2026-09-16T18:00:00.000Z',expiresAt:'2026-09-16T18:20:00.000Z',operation:{kind:'APP_RUN',appId:'cocwin',jobId:'v2-expiry-1',payload:{tool:'probe',cwd:'/home/cocwin/backend',args:[],timeout_ms:30000,max_bytes:65536}}})};
   const first=createRemoteBridgeWorker({...TRANSPORT,now:tick,store,github:{listOpenRequests:async()=>[v2],publishResult:vi.fn()},controller:{submit:async()=>({state:'QUEUED'}),status:vi.fn(),result:vi.fn()}});
   await first.runOnce();expect((await store.get(requestId))?.phase).toBe('SUBMITTED');
   clock=new Date('2026-09-16T18:25:00.000Z');
   const status=vi.fn(async()=>({state:'SUCCEEDED'})),result=vi.fn(async()=>({schema:'COCWIN_APP_EXECUTION_RESULT_V1',app:'cocwin',job:'v2-expiry-1',state:'SUCCEEDED',returncode:0,stdout:'ok',stderr:'',timed_out:false,truncated:false})),publish=vi.fn();
   const resumed=createRemoteBridgeWorker({...TRANSPORT,now:tick,store,github:{listOpenRequests:async()=>[v2],publishResult:publish},controller:{submit:vi.fn(),status,result}});
   const out=await resumed.runOnce();
   expect(out).toMatchObject({seen:1,pending:0,published:1,blocked:0,errors:0});
   expect(status).toHaveBeenCalledOnce();expect(result).toHaveBeenCalledOnce();
   expect(publish.mock.calls[0]![1]).toMatchObject({status:'PASS'});
 });

 it('never replays a durable result across repository or target-instance trust scopes',async()=>{
   const dir=await root(),store=createRemoteBridgeStore(dir,now);
   const first=createRemoteBridgeWorker({...TRANSPORT,now,store,github:{listOpenRequests:async()=>[issue()],publishResult:vi.fn()},controller:{submit:async()=>({state:'SUCCEEDED'}),status:vi.fn(),result:async()=>({schema:'COCWIN_APP_EXECUTION_RESULT_V1',app:'cocwin',job:'bridge-probe-1',state:'SUCCEEDED',returncode:0,stdout:'scope-a',stderr:'',timed_out:false,truncated:false})}});
   await first.runOnce();expect((await store.get('bridge.req.1'))?.phase).toBe('PUBLISHED');
   for(const changed of [
     {...TRANSPORT,repository:'example/other-control'},
     {...TRANSPORT,instanceId:'other-instance'},
   ]){
     const publish=vi.fn(),submit=vi.fn(),status=vi.fn(),result=vi.fn();
     const worker=createRemoteBridgeWorker({...changed,now,store,github:{listOpenRequests:async()=>[issue(90)],publishResult:publish},controller:{submit,status,result}});
     const out=await worker.runOnce();
     expect(out).toMatchObject({seen:1,pending:0,published:1,blocked:1,errors:0});
     expect(publish.mock.calls[0]![1]).toMatchObject({status:'BLOCKED',reason:'REQUEST_SCOPE_MISMATCH'});
     expect(submit).not.toHaveBeenCalled();expect(status).not.toHaveBeenCalled();expect(result).not.toHaveBeenCalled();
   }
 });

 it('round-robins bounded open requests so request 21 cannot starve behind 20 long-running jobs',async()=>{
   const dir=await root(),store=createRemoteBridgeStore(dir,now);
   const issues=Array.from({length:21},(_,index)=>{
     const n=index+1,requestId=`bridge.fair.${n}`,jobId=`fair-${n}`;
     return {number:100+n,title:`[COCWIN BRIDGE REQUEST] ${requestId}`,authorLogin:TRANSPORT.authorLogin,url:`https://github.com/example/rbridge-control/issues/${100+n}`,body:JSON.stringify({schema:'COCWIN_REMOTE_BRIDGE_REQUEST_V1',requestId,createdAt:'2026-09-16T18:00:00.000Z',expiresAt:'2026-09-16T18:20:00.000Z',appId:'cocwin',jobId,operation:'RUN',payload:{tool:'probe',cwd:'/home/cocwin/backend',args:[],timeout_ms:30000,max_bytes:65536}})};
   });
   const submit=vi.fn(async(...args:[string,string,unknown])=>{void args;return {state:'QUEUED'};}),status=vi.fn(async(...args:[string,string])=>{void args;return {state:'RUNNING'};});
   const worker=createRemoteBridgeWorker({...TRANSPORT,now,maxIssues:20,store,github:{listOpenRequests:async()=>issues,publishResult:vi.fn()},controller:{submit,status,result:vi.fn()}});
   expect(await worker.runOnce()).toMatchObject({seen:20,pending:20});
   expect(await store.get('bridge.fair.21')).toBeUndefined();
   expect(await worker.runOnce()).toMatchObject({seen:20,pending:20});
   expect((await store.get('bridge.fair.21'))?.phase).toBe('SUBMITTED');
   expect(submit.mock.calls.some(call=>call[1]==='fair-21')).toBe(true);
 });

});
describe('owner routing with preserved legacy reconciliation',()=>{
 const safeIssue=(id='new-safe',operation:Record<string,unknown>={kind:'HEALTH',action:'STATUS'},number=91)=>({number,title:'[COCWIN BRIDGE REQUEST] '+id,authorLogin:TRANSPORT.authorLogin,url:`https://github.com/${TRANSPORT.repository}/issues/${number}`,body:JSON.stringify({schema:'COCWIN_REMOTE_BRIDGE_REQUEST_V2',requestId:id,createdAt:'2026-09-16T18:00:00.000Z',expiresAt:'2026-09-16T18:20:00.000Z',operation})});
 function corePort(value:'CORE'|'PUBLICATION_UNAVAILABLE'='CORE'){return {admit:vi.fn(async()=>value),reconcileDeliveries:vi.fn(async()=>{})};}
 async function workerFixture(issues:GitHubBridgeIssue[]= [safeIssue()],value:'CORE'|'PUBLICATION_UNAVAILABLE'='CORE'){
  const dir=await root(),store=createRemoteBridgeStore(dir,now),core=corePort(value),ctl=controller(),snapshot=vi.fn(()=>({observed:'legacy'})),publish=vi.fn(),reservation=vi.fn(async()=>false);
  ctl.submit.mockResolvedValue({state:'SUCCEEDED'});ctl.result.mockResolvedValue({state:'SUCCEEDED'});
  const options={...TRANSPORT,now,store,github:{listOpenRequests:async()=>issues,publishResult:publish},githubCore:core,reservations:{isReserved:reservation},controller:ctl,health:{snapshot}};
  return {dir,store,core,ctl,snapshot,publish,reservation,options,worker:createRemoteBridgeWorker(options)};
 }
 it.each(['CORE','PUBLICATION_UNAVAILABLE'] as const)('new SAFE never falls back to legacy after %s',async value=>{const f=await workerFixture(undefined,value);await f.worker.runOnce();expect(f.core.admit).toHaveBeenCalledOnce();expect(f.snapshot).not.toHaveBeenCalled();expect(f.ctl.submit).not.toHaveBeenCalled();expect(f.publish).not.toHaveBeenCalled();expect(await f.store.get('new-safe')).toBeUndefined();});
 it('routes new FILE mutation and CHUNK to core without invoking old effect ports',async()=>{const rows=[safeIssue('new-write',{kind:'FILE',action:'WRITE_TEXT',target:'/mnt/data/new.txt',args:{content:'blocked'}}),v2ChunkIssue()];const f=await workerFixture(rows),execute=vi.fn(),chunks=chunkPort();await createRemoteBridgeWorker({...f.options,fileOps:{execute},chunkStore:chunks}).runOnce();expect(f.core.admit).toHaveBeenCalledTimes(2);expect(execute).not.toHaveBeenCalled();expect(chunks.putChunk).not.toHaveBeenCalled();expect(await f.store.get('new-write')).toBeUndefined();expect(await f.store.get('bridge.chunk.1')).toBeUndefined();});
 it('keeps a stored scoped V2 SAFE request on its existing legacy engine',async()=>{const f=await workerFixture();const {githubCore,reservations,...legacy}=f.options;void githubCore;void reservations;await createRemoteBridgeWorker(legacy).runOnce();expect(f.snapshot).toHaveBeenCalledOnce();f.reservation.mockResolvedValue(true);await f.worker.runOnce();expect(f.core.admit).not.toHaveBeenCalled();expect(f.snapshot).toHaveBeenCalledOnce();expect(f.publish.mock.calls.at(-1)![1]).toMatchObject({status:'PASS',reason:'REPLAY'});});
 it('preserves a stored V1 ID even when its new carrier body is V2 SAFE',async()=>{const row=safeIssue('bridge.req.1'),f=await workerFixture([row]);const {githubCore,reservations,...legacyOptions}=f.options;void githubCore;void reservations;const legacy=createRemoteBridgeWorker({...legacyOptions,github:{...f.options.github,listOpenRequests:async()=>[issue()]}});await legacy.runOnce();f.reservation.mockResolvedValue(true);await f.worker.runOnce();expect(f.core.admit).not.toHaveBeenCalled();expect(f.snapshot).not.toHaveBeenCalled();expect(f.publish.mock.calls.at(-1)![1]).toMatchObject({status:'BLOCKED',reason:'REQUEST_ID_COLLISION'});});
 it('blocks unscoped stored SAFE instead of moving it to core or re-executing it',async()=>{const f=await workerFixture(),{parseRemoteBridgeRequestV2,remoteBridgeRequestV2Digest}=await import('../../src/domain/remoteBridgeStage2Protocol.js');const row=safeIssue(),parsed=parseRemoteBridgeRequestV2({title:row.title,body:row.body,author:row.authorLogin,repository:TRANSPORT.repository,expectedAuthor:TRANSPORT.authorLogin,expectedRepository:TRANSPORT.repository,now:now()});const digest=remoteBridgeRequestV2Digest(parsed),stamp=now().toISOString();const {writeFile}=await import('node:fs/promises');await writeFile(join(f.dir,'new-safe.json'),JSON.stringify({schema:'COCWIN_REMOTE_BRIDGE_STORE_V1',requestId:'new-safe',requestSha256:digest,issueNumber:91,jobId:'old-job',phase:'SUBMITTED',createdAt:stamp,updatedAt:stamp}),{mode:0o600});f.reservation.mockResolvedValue(true);await f.worker.runOnce();expect(f.core.admit).not.toHaveBeenCalled();expect(f.snapshot).not.toHaveBeenCalled();expect(f.publish.mock.calls.at(-1)![1]).toMatchObject({status:'BLOCKED',reason:'REQUEST_SCOPE_MISMATCH'});expect((await f.store.get('new-safe'))?.phase).toBe('SUBMITTED');});
 it('does not create a fresh legacy claim for a FlowPilot-only reservation',async()=>{const f=await workerFixture(undefined,'PUBLICATION_UNAVAILABLE');f.reservation.mockResolvedValue(true);await f.worker.runOnce();expect(f.core.admit).toHaveBeenCalledOnce();expect(f.snapshot).not.toHaveBeenCalled();expect(await f.store.get('new-safe')).toBeUndefined();});
 it('keeps V1 and APP_RUN on legacy while the core guard blocks reserved IDs before controller submit',async()=>{const app=safeIssue('legacy-app',{kind:'APP_RUN',appId:'cocwin',jobId:'legacy-app',payload:{tool:'probe',cwd:'/home/cocwin/backend',args:[],timeout_ms:30000,max_bytes:65536}},92),f=await workerFixture([issue(),app]);await f.worker.runOnce();expect(f.ctl.submit).toHaveBeenCalledTimes(2);expect(f.core.admit).not.toHaveBeenCalled();const {createRBridgeLegacyClaimGuard}=await import('../../src/server/rbridgeLegacyReservations.js'),{createRBridgeOperationSerializer}=await import('../../src/server/rbridgeOperationSerializer.js');const store=createRemoteBridgeStore(await root(),now,{claimGuard:createRBridgeLegacyClaimGuard({serializer:createRBridgeOperationSerializer(),core:{async has(){return true;}}})});f.ctl.submit.mockClear();f.publish.mockClear();await createRemoteBridgeWorker({...f.options,store}).runOnce();expect(f.ctl.submit).not.toHaveBeenCalled();expect(f.publish).toHaveBeenCalledTimes(2);for(const call of f.publish.mock.calls)expect(call[1]).toMatchObject({status:'BLOCKED',reason:'RBRIDGE_CORE_LEGACY_ID_RESERVED'});expect(await store.get('bridge.req.1')).toBeUndefined();expect(await store.get('legacy-app')).toBeUndefined();});
 it('authenticates repository and bounds raw JSON before probing legacy reservations or core',async()=>{const deep:Record<string,unknown>={};let next=deep;for(let n=0;n<30;n++){const child={};next.child=child;next=child;}const row=safeIssue(),bad=[{...row,url:'https://github.com/foreign/control/issues/91'},{...row,authorLogin:'foreign'},{...row,body:'x'.repeat(65537)},{...row,body:JSON.stringify({...JSON.parse(row.body),extra:deep})}];const f=await workerFixture(bad),get=vi.spyOn(f.store,'get');await f.worker.runOnce();expect(f.reservation).not.toHaveBeenCalled();expect(get).not.toHaveBeenCalled();expect(f.core.admit).not.toHaveBeenCalled();expect(f.snapshot).not.toHaveBeenCalled();expect(f.ctl.submit).not.toHaveBeenCalled();expect(f.publish).not.toHaveBeenCalled();});
 it('routes an expired known core request to the core adapter rather than legacy expiry rejection',async()=>{const f=await workerFixture();await createRemoteBridgeWorker({...f.options,now:()=>new Date('2026-09-16T18:25:00.000Z')}).runOnce();expect(f.core.admit).toHaveBeenCalledOnce();expect(f.publish).not.toHaveBeenCalled();expect(f.snapshot).not.toHaveBeenCalled();});
 it('drains closed deliveries in a bounded batch independent of open issues and list failure',async()=>{const f=await workerFixture([]);await f.worker.runOnce();expect(f.core.reconcileDeliveries).toHaveBeenCalledExactlyOnceWith(20);f.core.reconcileDeliveries.mockClear();await expect(createRemoteBridgeWorker({...f.options,github:{...f.options.github,async listOpenRequests(){throw new Error('LIST_FAILED');}}}).runOnce()).rejects.toThrow('LIST_FAILED');expect(f.core.reconcileDeliveries).toHaveBeenCalledExactlyOnceWith(20);});
});
