import {createHash} from 'node:crypto';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {afterEach,describe,expect,it,vi} from 'vitest';
import {createRemoteBridgeStore} from '../../src/server/remoteBridgeStore.js';import {createRemoteBridgeWorker} from '../../src/server/remoteBridgeWorker.js';
const TRANSPORT={repository:'example/rbridge-control',authorLogin:'bridge-owner',instanceId:'test-instance'} as const;
const roots:string[]=[];async function root(){const p=await mkdtemp(join(tmpdir(),'bridge-worker-'));roots.push(p);return p;}afterEach(async()=>{await Promise.all(roots.splice(0).map(p=>rm(p,{recursive:true,force:true})));});
const body=(max=262144)=>JSON.stringify({schema:'COCWIN_REMOTE_BRIDGE_REQUEST_V1',requestId:'bridge.req.1',createdAt:'2026-09-16T18:00:00.000Z',expiresAt:'2026-09-16T18:20:00.000Z',appId:'cocwin',jobId:'bridge-probe-1',operation:'RUN',payload:{tool:'probe',cwd:'/home/cocwin/backend',args:[],timeout_ms:30000,max_bytes:max}});
const issue=(number=49,max=262144)=>({number,title:'[COCWIN BRIDGE REQUEST] bridge.req.1',body:body(max),authorLogin:'bridge-owner',url:`https://github.com/example/rbridge-control/issues/${number}`});
const now=()=>new Date('2026-09-16T18:10:00.000Z');
const sha=(value:Buffer|string)=>createHash('sha256').update(value).digest('hex');
const chunk=Buffer.from('chunk-worker-payload');
const chunkArgs={index:0,count:1,dataBase64:chunk.toString('base64'),chunkSha256:sha(chunk),objectSha256:sha(chunk),expiresAt:'2026-09-16T18:20:00.000Z'};
const v2ChunkBody=(requestId='bridge.chunk.1',args:Record<string,unknown>=chunkArgs)=>JSON.stringify({schema:'COCWIN_REMOTE_BRIDGE_REQUEST_V2',requestId,createdAt:'2026-09-16T18:00:00.000Z',expiresAt:'2026-09-16T18:20:00.000Z',operation:{kind:'CHUNK',action:'PUT',transferId:'tx.worker',args}});
const v2ChunkIssue=(number=70,requestId='bridge.chunk.1',args:Record<string,unknown>=chunkArgs)=>({number,title:`[COCWIN BRIDGE REQUEST] ${requestId}`,body:v2ChunkBody(requestId,args),authorLogin:'bridge-owner',url:`https://github.com/example/rbridge-control/issues/${number}`});
const controller=()=>({submit:vi.fn(),status:vi.fn(),result:vi.fn()});
const resultPut=(state:'STORED'|'REPLAY')=>vi.fn(async(input:unknown)=>{void input;return {state,index:0};});
const chunkPort=(put=resultPut('STORED'))=>({putChunk:put,getChunk:vi.fn(),finalizeTransfer:vi.fn()});

describe('remote bridge worker',()=>{
 it('durably marks SUBMITTED before first submit and leaves request pending when queued',async()=>{const dir=await root(),events:string[]=[];const store=createRemoteBridgeStore(dir,now),published:unknown[]=[];const worker=createRemoteBridgeWorker({...TRANSPORT,now,store,github:{listOpenRequests:async()=>[issue()],publishResult:async(_n,r)=>{published.push(r);}},controller:{submit:async()=>{events.push('submit');expect((await store.get('bridge.req.1'))?.phase).toBe('SUBMITTED');return {state:'QUEUED'};},status:vi.fn(),result:vi.fn()}});const out=await worker.runOnce();expect(out).toMatchObject({seen:1,pending:1,published:0});expect(events).toEqual(['submit']);expect(published).toHaveLength(0);});
 it('reconciles a durable SUBMITTED request by status/result without resubmitting',async()=>{const dir=await root(),store=createRemoteBridgeStore(dir,now);const worker1=createRemoteBridgeWorker({...TRANSPORT,now,store,github:{listOpenRequests:async()=>[issue()],publishResult:vi.fn()},controller:{submit:async()=>{throw new Error('transport lost after possible submit');},status:vi.fn(),result:vi.fn()}});await worker1.runOnce();expect((await store.get('bridge.req.1'))?.phase).toBe('SUBMITTED');const submit=vi.fn(),publish=vi.fn();const worker2=createRemoteBridgeWorker({...TRANSPORT,now,store,github:{listOpenRequests:async()=>[issue()],publishResult:publish},controller:{submit,status:async()=>({state:'SUCCEEDED'}),result:async()=>({schema:'COCWIN_APP_EXECUTION_RESULT_V1',app:'cocwin',job:'bridge-probe-1',state:'SUCCEEDED',returncode:0,stdout:'ok',stderr:'',timed_out:false,truncated:false})}});await worker2.runOnce();expect(submit).not.toHaveBeenCalled();expect(publish).toHaveBeenCalledTimes(1);expect(publish.mock.calls[0]![1]).toMatchObject({schema:'COCWIN_REMOTE_BRIDGE_RESULT_V1',requestId:'bridge.req.1',issueNumber:49,status:'PASS'});expect((await store.get('bridge.req.1'))?.phase).toBe('PUBLISHED');});
 it('replays terminal execution to a duplicate issue without execution and blocks digest collision',async()=>{const dir=await root(),store=createRemoteBridgeStore(dir,now),submit=vi.fn(),publish=vi.fn();const first=createRemoteBridgeWorker({...TRANSPORT,now,store,github:{listOpenRequests:async()=>[issue()],publishResult:async()=>{}},controller:{submit:async()=>({state:'SUCCEEDED'}),status:vi.fn(),result:async()=>({schema:'COCWIN_APP_EXECUTION_RESULT_V1',app:'cocwin',job:'bridge-probe-1',state:'SUCCEEDED',returncode:0,stdout:'ok',stderr:'',timed_out:false,truncated:false})}});await first.runOnce();const replay=createRemoteBridgeWorker({...TRANSPORT,now,store,github:{listOpenRequests:async()=>[issue(50)],publishResult:publish},controller:{submit,status:vi.fn(),result:vi.fn()}});await replay.runOnce();expect(submit).not.toHaveBeenCalled();expect(publish.mock.calls[0]![0]).toBe(50);expect(publish.mock.calls[0]![1]).toMatchObject({status:'PASS',reason:'REPLAY'});const collision=createRemoteBridgeWorker({...TRANSPORT,now,store,github:{listOpenRequests:async()=>[issue(51,262145)],publishResult:publish},controller:{submit,status:vi.fn(),result:vi.fn()}});await collision.runOnce();expect(publish.mock.calls.at(-1)![1]).toMatchObject({status:'BLOCKED',reason:'REQUEST_ID_COLLISION'});expect(submit).not.toHaveBeenCalled();});
 it('terminalizes a definitive controller BLOCKED during reconciliation without calling result or resubmitting',async()=>{const dir=await root(),store=createRemoteBridgeStore(dir,now);const first=createRemoteBridgeWorker({...TRANSPORT,now,store,github:{listOpenRequests:async()=>[issue()],publishResult:vi.fn()},controller:{submit:async()=>({state:'QUEUED'}),status:vi.fn(),result:vi.fn()}});await first.runOnce();expect((await store.get('bridge.req.1'))?.phase).toBe('SUBMITTED');const submit=vi.fn(),result=vi.fn(async()=>({state:'SUCCEEDED'})),publish=vi.fn();const second=createRemoteBridgeWorker({...TRANSPORT,now,store,github:{listOpenRequests:async()=>[issue()],publishResult:publish},controller:{submit,status:async()=>({schema:'COCWIN_APP_EXECUTION_STATUS_V1',app:'cocwin',job:'bridge-probe-1',state:'BLOCKED',reason:'application execution identity is not configured'}),result}});await second.runOnce();expect(submit).not.toHaveBeenCalled();expect(result).not.toHaveBeenCalled();expect(publish).toHaveBeenCalledTimes(1);expect(publish.mock.calls[0]![1]).toMatchObject({status:'BLOCKED',reason:'application execution identity is not configured'});expect((await store.get('bridge.req.1'))?.phase).toBe('PUBLISHED');});
 it('blocks stale or malformed requests without touching controller',async()=>{const dir=await root(),store=createRemoteBridgeStore(dir,()=>new Date('2026-09-16T18:25:00.000Z')),submit=vi.fn(),publish=vi.fn();const worker=createRemoteBridgeWorker({...TRANSPORT,now:()=>new Date('2026-09-16T18:25:00.000Z'),store,github:{listOpenRequests:async()=>[issue()],publishResult:publish},controller:{submit,status:vi.fn(),result:vi.fn()}});await worker.runOnce();expect(submit).not.toHaveBeenCalled();expect(publish.mock.calls[0]![1]).toMatchObject({status:'BLOCKED',reason:'REMOTE_BRIDGE_REQUEST_EXPIRED'});});
 it('terminates durable SUBMITTED request when controller status proves definitive BLOCKED',async()=>{const dir=await root(),store=createRemoteBridgeStore(dir,now);const {parseRemoteBridgeRequest,remoteBridgeRequestDigest}=await import('../../src/domain/remoteBridgeProtocol.js');const q=parseRemoteBridgeRequest({title:issue().title,body:issue().body,authorLogin:'bridge-owner',expectedAuthorLogin:TRANSPORT.authorLogin,now:now()});const d=remoteBridgeRequestDigest(q);await store.claim({requestId:q.requestId,requestSha256:d,scopeSha256:sha(JSON.stringify({repository:TRANSPORT.repository,authorLogin:TRANSPORT.authorLogin,instanceId:TRANSPORT.instanceId})),issueNumber:49,jobId:q.jobId});await store.markSubmitted(q.requestId,d);const submit=vi.fn(),result=vi.fn(),publish=vi.fn();const worker=createRemoteBridgeWorker({...TRANSPORT,now,store,github:{listOpenRequests:async()=>[issue()],publishResult:publish},controller:{submit,status:async()=>({schema:'COCWIN_APP_EXECUTION_STATUS_V1',app:'cocwin',job:'bridge-probe-1',state:'BLOCKED',reason:'application execution identity is not configured'}),result}});const out=await worker.runOnce();expect(submit).not.toHaveBeenCalled();expect(result).not.toHaveBeenCalled();expect(out).toMatchObject({seen:1,pending:0,published:1,blocked:1,errors:0});expect(publish.mock.calls[0]![1]).toMatchObject({status:'BLOCKED',reason:'application execution identity is not configured'});expect((await store.get(q.requestId))?.phase).toBe('PUBLISHED');});
 it('routes a V2 CHUNK PUT through the durable chunk port without touching controller',async()=>{const dir=await root(),store=createRemoteBridgeStore(dir,now),publish=vi.fn(),put=resultPut('STORED'),ctl=controller();const worker=createRemoteBridgeWorker({...TRANSPORT,now,store,github:{listOpenRequests:async()=>[v2ChunkIssue()],publishResult:publish},controller:ctl,chunkStore:chunkPort(put)});const out=await worker.runOnce();expect(out).toMatchObject({seen:1,pending:0,published:1,blocked:0,errors:0});expect(put).toHaveBeenCalledOnce();expect(put.mock.calls[0]![0]).toEqual({transferId:'tx.worker',...chunkArgs});expect(ctl.submit).not.toHaveBeenCalled();expect(publish.mock.calls[0]![1]).toMatchObject({schema:'COCWIN_REMOTE_BRIDGE_RESULT_V2',requestId:'bridge.chunk.1',status:'PASS',operationResult:{state:'STORED',index:0}});expect((await store.get('bridge.chunk.1'))?.phase).toBe('PUBLISHED');});
 it('replays a published V2 chunk request without executing the chunk port twice',async()=>{const dir=await root(),store=createRemoteBridgeStore(dir,now),put=resultPut('STORED'),port=chunkPort(put);const first=createRemoteBridgeWorker({...TRANSPORT,now,store,github:{listOpenRequests:async()=>[v2ChunkIssue()],publishResult:vi.fn()},controller:controller(),chunkStore:port});await first.runOnce();const publish=vi.fn();const replay=createRemoteBridgeWorker({...TRANSPORT,now,store,github:{listOpenRequests:async()=>[v2ChunkIssue(71)],publishResult:publish},controller:controller(),chunkStore:port});await replay.runOnce();expect(put).toHaveBeenCalledTimes(1);expect(publish.mock.calls[0]![1]).toMatchObject({schema:'COCWIN_REMOTE_BRIDGE_RESULT_V2',status:'PASS',reason:'REPLAY'});});
 it('retries a durable SUBMITTED V2 chunk operation after a crash using the same idempotent transfer identity',async()=>{const dir=await root(),store=createRemoteBridgeStore(dir,now),crashing=vi.fn(async(input:unknown)=>{void input;throw new Error('simulated crash after durable SUBMITTED');});const first=createRemoteBridgeWorker({...TRANSPORT,now,store,github:{listOpenRequests:async()=>[v2ChunkIssue()],publishResult:vi.fn()},controller:controller(),chunkStore:chunkPort(crashing)});const firstOut=await first.runOnce();expect(firstOut.errors).toBe(1);expect((await store.get('bridge.chunk.1'))?.phase).toBe('SUBMITTED');const resumed=resultPut('REPLAY'),publish=vi.fn();const second=createRemoteBridgeWorker({...TRANSPORT,now,store,github:{listOpenRequests:async()=>[v2ChunkIssue()],publishResult:publish},controller:controller(),chunkStore:chunkPort(resumed)});await second.runOnce();expect(resumed).toHaveBeenCalledOnce();expect(publish.mock.calls[0]![1]).toMatchObject({schema:'COCWIN_REMOTE_BRIDGE_RESULT_V2',status:'PASS',operationResult:{state:'REPLAY',index:0}});expect((await store.get('bridge.chunk.1'))?.phase).toBe('PUBLISHED');});

 it('continues tracking an accepted V1 request after its acceptance TTL expires',async()=>{
   const dir=await root();let clock=new Date('2026-09-16T18:10:00.000Z');const tick=()=>clock;
   const store=createRemoteBridgeStore(dir,tick);
   const first=createRemoteBridgeWorker({...TRANSPORT,now:tick,store,github:{listOpenRequests:async()=>[issue()],publishResult:vi.fn()},controller:{submit:async()=>({state:'QUEUED'}),status:vi.fn(),result:vi.fn()}});
   await first.runOnce();expect((await store.get('bridge.req.1'))?.phase).toBe('SUBMITTED');
   clock=new Date('2026-09-16T18:25:00.000Z');
   const status=vi.fn(async()=>({state:'SUCCEEDED'})),result=vi.fn(async()=>({schema:'COCWIN_APP_EXECUTION_RESULT_V1',app:'cocwin',job:'bridge-probe-1',state:'SUCCEEDED',returncode:0,stdout:'ok',stderr:'',timed_out:false,truncated:false})),publish=vi.fn();
   const resumed=createRemoteBridgeWorker({...TRANSPORT,now:tick,store,github:{listOpenRequests:async()=>[issue()],publishResult:publish},controller:{submit:vi.fn(),status,result}});
   const out=await resumed.runOnce();
   expect(out).toMatchObject({seen:1,pending:0,published:1,blocked:0,errors:0});
   expect(status).toHaveBeenCalledOnce();expect(result).toHaveBeenCalledOnce();
   expect(publish.mock.calls[0]![1]).toMatchObject({status:'PASS'});
 });

 it('continues tracking an accepted V2 APP_RUN after its acceptance TTL expires',async()=>{
   const dir=await root();let clock=new Date('2026-09-16T18:10:00.000Z');const tick=()=>clock;
   const store=createRemoteBridgeStore(dir,tick),requestId='bridge.v2.expiry.1';
   const v2={number:81,title:`[COCWIN BRIDGE REQUEST] ${requestId}`,authorLogin:TRANSPORT.authorLogin,url:'https://github.com/example/rbridge-control/issues/81',body:JSON.stringify({schema:'COCWIN_REMOTE_BRIDGE_REQUEST_V2',requestId,createdAt:'2026-09-16T18:00:00.000Z',expiresAt:'2026-09-16T18:20:00.000Z',operation:{kind:'APP_RUN',appId:'cocwin',jobId:'v2-expiry-1',payload:{tool:'probe',cwd:'/home/cocwin/backend',args:[],timeout_ms:30000,max_bytes:65536}}})};
   const first=createRemoteBridgeWorker({...TRANSPORT,now:tick,store,github:{listOpenRequests:async()=>[v2],publishResult:vi.fn()},controller:{submit:async()=>({state:'QUEUED'}),status:vi.fn(),result:vi.fn()}});
   await first.runOnce();expect((await store.get(requestId))?.phase).toBe('SUBMITTED');
   clock=new Date('2026-09-16T18:25:00.000Z');
   const status=vi.fn(async()=>({state:'SUCCEEDED'})),result=vi.fn(async()=>({schema:'COCWIN_APP_EXECUTION_RESULT_V1',app:'cocwin',job:'v2-expiry-1',state:'SUCCEEDED',returncode:0,stdout:'ok',stderr:'',timed_out:false,truncated:false})),publish=vi.fn();
   const resumed=createRemoteBridgeWorker({...TRANSPORT,now:tick,store,github:{listOpenRequests:async()=>[v2],publishResult:publish},controller:{submit:vi.fn(),status,result}});
   const out=await resumed.runOnce();
   expect(out).toMatchObject({seen:1,pending:0,published:1,blocked:0,errors:0});
   expect(status).toHaveBeenCalledOnce();expect(result).toHaveBeenCalledOnce();
   expect(publish.mock.calls[0]![1]).toMatchObject({status:'PASS'});
 });

 it('never replays a durable result across repository or target-instance trust scopes',async()=>{
   const dir=await root(),store=createRemoteBridgeStore(dir,now);
   const first=createRemoteBridgeWorker({...TRANSPORT,now,store,github:{listOpenRequests:async()=>[issue()],publishResult:vi.fn()},controller:{submit:async()=>({state:'SUCCEEDED'}),status:vi.fn(),result:async()=>({schema:'COCWIN_APP_EXECUTION_RESULT_V1',app:'cocwin',job:'bridge-probe-1',state:'SUCCEEDED',returncode:0,stdout:'scope-a',stderr:'',timed_out:false,truncated:false})}});
   await first.runOnce();expect((await store.get('bridge.req.1'))?.phase).toBe('PUBLISHED');
   for(const changed of [
     {...TRANSPORT,repository:'example/other-control'},
     {...TRANSPORT,instanceId:'other-instance'},
   ]){
     const publish=vi.fn(),submit=vi.fn(),status=vi.fn(),result=vi.fn();
     const worker=createRemoteBridgeWorker({...changed,now,store,github:{listOpenRequests:async()=>[issue(90)],publishResult:publish},controller:{submit,status,result}});
     const out=await worker.runOnce();
     expect(out).toMatchObject({seen:1,pending:0,published:1,blocked:1,errors:0});
     expect(publish.mock.calls[0]![1]).toMatchObject({status:'BLOCKED',reason:'REQUEST_SCOPE_MISMATCH'});
     expect(submit).not.toHaveBeenCalled();expect(status).not.toHaveBeenCalled();expect(result).not.toHaveBeenCalled();
   }
 });

 it('round-robins bounded open requests so request 21 cannot starve behind 20 long-running jobs',async()=>{
   const dir=await root(),store=createRemoteBridgeStore(dir,now);
   const issues=Array.from({length:21},(_,index)=>{
     const n=index+1,requestId=`bridge.fair.${n}`,jobId=`fair-${n}`;
     return {number:100+n,title:`[COCWIN BRIDGE REQUEST] ${requestId}`,authorLogin:TRANSPORT.authorLogin,url:`https://github.com/example/rbridge-control/issues/${100+n}`,body:JSON.stringify({schema:'COCWIN_REMOTE_BRIDGE_REQUEST_V1',requestId,createdAt:'2026-09-16T18:00:00.000Z',expiresAt:'2026-09-16T18:20:00.000Z',appId:'cocwin',jobId,operation:'RUN',payload:{tool:'probe',cwd:'/home/cocwin/backend',args:[],timeout_ms:30000,max_bytes:65536}})};
   });
   const submit=vi.fn(async(_app:string,_job:string,_payload:unknown)=>({state:'QUEUED'})),status=vi.fn(async(_app:string,_job:string)=>({state:'RUNNING'}));
   const worker=createRemoteBridgeWorker({...TRANSPORT,now,maxIssues:20,store,github:{listOpenRequests:async()=>issues,publishResult:vi.fn()},controller:{submit,status,result:vi.fn()}});
   expect(await worker.runOnce()).toMatchObject({seen:20,pending:20});
   expect(await store.get('bridge.fair.21')).toBeUndefined();
   expect(await worker.runOnce()).toMatchObject({seen:20,pending:20});
   expect((await store.get('bridge.fair.21'))?.phase).toBe('SUBMITTED');
   expect(submit.mock.calls.some(call=>call[1]==='fair-21')).toBe(true);
 });

});